spring.application.name=spring-ai-gift

app.ai.provider=claude

# Google Gemini
spring.ai.google.genai.api-key=teste
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite

# AWS Bedrock
spring.ai.bedrock.aws.region=ap-northeast-2
spring.ai.bedrock.converse.chat.options.model=test

# Claude
claude.model=claude-sonnet-4-20250514
claude.working-dir=test
